public class HW1{

    public static void main (String args[]){
    // Write an if/else statement for the following requirements:
    // If student gets 90 or higher: console log  A
    // If students get 80 or above: console log B
    // If students get 70 or above: console log C
    // If students get 55 or above: console log D
    // Any grade lower than 55 is F
        int studentScore = 65;
        if (studentScore >)
        }
}